### ISSUE TITLE
Publish to Hex

### ISSUE THREAD

**Issue by lpil** [zadean/yaccety_sax#4]
Hello!

Would it be possible to get this package on Hex? So it can be included more easily in other projects.

Thanks,
Louis

**Comment by zadean** [comment]
Hey Louis,

Yes of course! I'll need to clean up a little bit of the specs and docs, and will publish it!

**Comment by zadean** [comment]
Bam!! https://hex.pm/packages/yaccety_sax 😸

**Comment by lpil** [comment]
Wonderful! Thank you
